export default {
    READ_LABELS: 'READ_LABELS',
    EXPORT_LABOR_TICKET_DATA: 'EXPORT_LABOR_TICKET_DATA',
    EMPLOYEE_LABELS_LASER: 'EMPLOYEE_LABELS_LASER',
    PRODUCTION_LABELS_LASER: 'PRODUCTION_LABELS_LASER',
    EMPLOYEE_LABELS_DOT_MATRIX: 'EMPLOYEE_LABELS_DOT_MATRIX',
    PRODUCTION_LABELS_DOT_MATRIX: 'PRODUCTION_LABELS_DOT_MATRIX',
}