export default {
    LABOR : 'SUB_NAV_LABOR',
    PRODUCTS: 'SUB_NAV_PRODUCTS',
    LABOR_ACTIVITIES: 'LABOR_ACTIVITIES',
    PRODUCTION_ACTIVITIES: 'PRODUCTION_ACTIVITIES',
    LABOR_QUERIES: 'LABOR_QUERIES',
    PRODUCTION_QUERIES: 'PRODUCTION_QUERIES',
    LABOR_REPORTS: 'LABOR_REPORTS',
    PRODUCT_REPORTS: 'PRODUCT_REPORTS',
    COST_BOOK_REPORT: 'COST_BOOK_REPORT',
    LABOR_LISTS: 'LABOR_LISTS',
    PRODUCT_LISTS: 'PRODUCT_LISTS',

}